// Package wave Code generated by swaggo/swag. DO NOT EDIT
package wave

import "github.com/swaggo/swag"

const docTemplatewave = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfowave holds exported Swagger Info so clients can modify it
var SwaggerInfowave = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "wave",
	Description:      "",
	InfoInstanceName: "wave",
	SwaggerTemplate:  docTemplatewave,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfowave.InstanceName(), SwaggerInfowave)
}
