version: '3.9'

services:

  server:
    container_name: server
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - minio
      - postgres

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --console-address ":9001" /data/radium/minio
    environment:
      MINIO_ROOT_USER: useruseruser
      MINIO_ROOT_PASSWORD: useruseruser
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - radium_minio:/data/radium/minio

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/radium/postgres
    volumes:
      - radium_pg:/data/radium/postgres
    ports:
      - "5432:5432"
    restart: "always"

volumes:
  radium_pg:
    name: radium_pg
  radium_minio:
    name: radium_minio