version: '3.9'

services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - minio
      - postgres
      - centrifugo

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --console-address ":9001" /data/radium/minio
    environment:
      MINIO_ROOT_USER: useruseruser
      MINIO_ROOT_PASSWORD: useruseruser
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - radium_minio:/data/radium/minio

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/radium/postgres
    volumes:
      - radium_pg:/data/radium/postgres
    ports:
      - "5432:5432"
    restart: "always"

  integration-radium:
    build:
      context: .
      dockerfile: integration-test/radium/Dockerfile
    container_name: integration
    image: integration-radium
    depends_on:
      - server

  integration-wave:
    build:
      context: .
      dockerfile: integration-test/wave/Dockerfile
    container_name: integration-wave
    image: integration-wave
    depends_on:
      - server

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5
    volumes:
      - ./config/centrifugo.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - "6969:6969"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  radium_pg:
    name: radium_pg
  radium_minio:
    name: radium_minio
