// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/radium-rtf/radium-backend/internal/entity"
)

func newGroup(db *gorm.DB, opts ...gen.DOOption) group {
	_group := group{}

	_group.groupDo.UseDB(db, opts...)
	_group.groupDo.UseModel(&entity.Group{})

	tableName := _group.groupDo.TableName()
	_group.ALL = field.NewAsterisk(tableName)
	_group.Id = field.NewField(tableName, "id")
	_group.CreatedAt = field.NewTime(tableName, "created_at")
	_group.UpdatedAt = field.NewTime(tableName, "updated_at")
	_group.DeletedAt = field.NewField(tableName, "deleted_at")
	_group.Name = field.NewString(tableName, "name")
	_group.InviteCode = field.NewString(tableName, "invite_code")
	_group.Courses = groupManyToManyCourses{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Courses", "entity.Course"),
		Links: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Courses.Links", "entity.Link"),
		},
		Modules: struct {
			field.RelationField
			Pages struct {
				field.RelationField
				Sections struct {
					field.RelationField
					TextSection struct {
						field.RelationField
					}
					ChoiceSection struct {
						field.RelationField
					}
					MultiChoiceSection struct {
						field.RelationField
					}
					ShortAnswerSection struct {
						field.RelationField
					}
					AnswerSection struct {
						field.RelationField
					}
					CodeSection struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("Courses.Modules", "entity.Module"),
			Pages: struct {
				field.RelationField
				Sections struct {
					field.RelationField
					TextSection struct {
						field.RelationField
					}
					ChoiceSection struct {
						field.RelationField
					}
					MultiChoiceSection struct {
						field.RelationField
					}
					ShortAnswerSection struct {
						field.RelationField
					}
					AnswerSection struct {
						field.RelationField
					}
					CodeSection struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Courses.Modules.Pages", "entity.Page"),
				Sections: struct {
					field.RelationField
					TextSection struct {
						field.RelationField
					}
					ChoiceSection struct {
						field.RelationField
					}
					MultiChoiceSection struct {
						field.RelationField
					}
					ShortAnswerSection struct {
						field.RelationField
					}
					AnswerSection struct {
						field.RelationField
					}
					CodeSection struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Courses.Modules.Pages.Sections", "entity.Section"),
					TextSection: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Courses.Modules.Pages.Sections.TextSection", "entity.TextSection"),
					},
					ChoiceSection: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Courses.Modules.Pages.Sections.ChoiceSection", "entity.ChoiceSection"),
					},
					MultiChoiceSection: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Courses.Modules.Pages.Sections.MultiChoiceSection", "entity.MultiChoiceSection"),
					},
					ShortAnswerSection: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Courses.Modules.Pages.Sections.ShortAnswerSection", "entity.ShortAnswerSection"),
					},
					AnswerSection: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Courses.Modules.Pages.Sections.AnswerSection", "entity.AnswerSection"),
					},
					CodeSection: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Courses.Modules.Pages.Sections.CodeSection", "entity.CodeSection"),
					},
				},
			},
		},
		Authors: struct {
			field.RelationField
			Sessions struct {
				field.RelationField
			}
			Courses struct {
				field.RelationField
			}
			Groups struct {
				field.RelationField
				Courses struct {
					field.RelationField
				}
				Students struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Courses.Authors", "entity.User"),
			Sessions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Courses.Authors.Sessions", "entity.Session"),
			},
			Courses: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Courses.Authors.Courses", "entity.Course"),
			},
			Groups: struct {
				field.RelationField
				Courses struct {
					field.RelationField
				}
				Students struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Courses.Authors.Groups", "entity.Group"),
				Courses: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Courses.Authors.Groups.Courses", "entity.Course"),
				},
				Students: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Courses.Authors.Groups.Students", "entity.User"),
				},
			},
		},
		Students: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Courses.Students", "entity.User"),
		},
		Groups: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Courses.Groups", "entity.Group"),
		},
	}

	_group.Students = groupManyToManyStudents{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Students", "entity.User"),
	}

	_group.fillFieldMap()

	return _group
}

type group struct {
	groupDo groupDo

	ALL        field.Asterisk
	Id         field.Field
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field
	Name       field.String
	InviteCode field.String
	Courses    groupManyToManyCourses

	Students groupManyToManyStudents

	fieldMap map[string]field.Expr
}

func (g group) Table(newTableName string) *group {
	g.groupDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g group) As(alias string) *group {
	g.groupDo.DO = *(g.groupDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *group) updateTableName(table string) *group {
	g.ALL = field.NewAsterisk(table)
	g.Id = field.NewField(table, "id")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.DeletedAt = field.NewField(table, "deleted_at")
	g.Name = field.NewString(table, "name")
	g.InviteCode = field.NewString(table, "invite_code")

	g.fillFieldMap()

	return g
}

func (g *group) WithContext(ctx context.Context) IGroupDo { return g.groupDo.WithContext(ctx) }

func (g group) TableName() string { return g.groupDo.TableName() }

func (g group) Alias() string { return g.groupDo.Alias() }

func (g *group) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *group) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.Id
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["deleted_at"] = g.DeletedAt
	g.fieldMap["name"] = g.Name
	g.fieldMap["invite_code"] = g.InviteCode

}

func (g group) clone(db *gorm.DB) group {
	g.groupDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g group) replaceDB(db *gorm.DB) group {
	g.groupDo.ReplaceDB(db)
	return g
}

type groupManyToManyCourses struct {
	db *gorm.DB

	field.RelationField

	Links struct {
		field.RelationField
	}
	Modules struct {
		field.RelationField
		Pages struct {
			field.RelationField
			Sections struct {
				field.RelationField
				TextSection struct {
					field.RelationField
				}
				ChoiceSection struct {
					field.RelationField
				}
				MultiChoiceSection struct {
					field.RelationField
				}
				ShortAnswerSection struct {
					field.RelationField
				}
				AnswerSection struct {
					field.RelationField
				}
				CodeSection struct {
					field.RelationField
				}
			}
		}
	}
	Authors struct {
		field.RelationField
		Sessions struct {
			field.RelationField
		}
		Courses struct {
			field.RelationField
		}
		Groups struct {
			field.RelationField
			Courses struct {
				field.RelationField
			}
			Students struct {
				field.RelationField
			}
		}
	}
	Students struct {
		field.RelationField
	}
	Groups struct {
		field.RelationField
	}
}

func (a groupManyToManyCourses) Where(conds ...field.Expr) *groupManyToManyCourses {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a groupManyToManyCourses) WithContext(ctx context.Context) *groupManyToManyCourses {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a groupManyToManyCourses) Session(session *gorm.Session) *groupManyToManyCourses {
	a.db = a.db.Session(session)
	return &a
}

func (a groupManyToManyCourses) Model(m *entity.Group) *groupManyToManyCoursesTx {
	return &groupManyToManyCoursesTx{a.db.Model(m).Association(a.Name())}
}

type groupManyToManyCoursesTx struct{ tx *gorm.Association }

func (a groupManyToManyCoursesTx) Find() (result []*entity.Course, err error) {
	return result, a.tx.Find(&result)
}

func (a groupManyToManyCoursesTx) Append(values ...*entity.Course) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a groupManyToManyCoursesTx) Replace(values ...*entity.Course) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a groupManyToManyCoursesTx) Delete(values ...*entity.Course) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a groupManyToManyCoursesTx) Clear() error {
	return a.tx.Clear()
}

func (a groupManyToManyCoursesTx) Count() int64 {
	return a.tx.Count()
}

type groupManyToManyStudents struct {
	db *gorm.DB

	field.RelationField
}

func (a groupManyToManyStudents) Where(conds ...field.Expr) *groupManyToManyStudents {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a groupManyToManyStudents) WithContext(ctx context.Context) *groupManyToManyStudents {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a groupManyToManyStudents) Session(session *gorm.Session) *groupManyToManyStudents {
	a.db = a.db.Session(session)
	return &a
}

func (a groupManyToManyStudents) Model(m *entity.Group) *groupManyToManyStudentsTx {
	return &groupManyToManyStudentsTx{a.db.Model(m).Association(a.Name())}
}

type groupManyToManyStudentsTx struct{ tx *gorm.Association }

func (a groupManyToManyStudentsTx) Find() (result []*entity.User, err error) {
	return result, a.tx.Find(&result)
}

func (a groupManyToManyStudentsTx) Append(values ...*entity.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a groupManyToManyStudentsTx) Replace(values ...*entity.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a groupManyToManyStudentsTx) Delete(values ...*entity.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a groupManyToManyStudentsTx) Clear() error {
	return a.tx.Clear()
}

func (a groupManyToManyStudentsTx) Count() int64 {
	return a.tx.Count()
}

type groupDo struct{ gen.DO }

type IGroupDo interface {
	gen.SubQuery
	Debug() IGroupDo
	WithContext(ctx context.Context) IGroupDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGroupDo
	WriteDB() IGroupDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGroupDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGroupDo
	Not(conds ...gen.Condition) IGroupDo
	Or(conds ...gen.Condition) IGroupDo
	Select(conds ...field.Expr) IGroupDo
	Where(conds ...gen.Condition) IGroupDo
	Order(conds ...field.Expr) IGroupDo
	Distinct(cols ...field.Expr) IGroupDo
	Omit(cols ...field.Expr) IGroupDo
	Join(table schema.Tabler, on ...field.Expr) IGroupDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGroupDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGroupDo
	Group(cols ...field.Expr) IGroupDo
	Having(conds ...gen.Condition) IGroupDo
	Limit(limit int) IGroupDo
	Offset(offset int) IGroupDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupDo
	Unscoped() IGroupDo
	Create(values ...*entity.Group) error
	CreateInBatches(values []*entity.Group, batchSize int) error
	Save(values ...*entity.Group) error
	First() (*entity.Group, error)
	Take() (*entity.Group, error)
	Last() (*entity.Group, error)
	Find() ([]*entity.Group, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Group, err error)
	FindInBatches(result *[]*entity.Group, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entity.Group) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGroupDo
	Assign(attrs ...field.AssignExpr) IGroupDo
	Joins(fields ...field.RelationField) IGroupDo
	Preload(fields ...field.RelationField) IGroupDo
	FirstOrInit() (*entity.Group, error)
	FirstOrCreate() (*entity.Group, error)
	FindByPage(offset int, limit int) (result []*entity.Group, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGroupDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g groupDo) Debug() IGroupDo {
	return g.withDO(g.DO.Debug())
}

func (g groupDo) WithContext(ctx context.Context) IGroupDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g groupDo) ReadDB() IGroupDo {
	return g.Clauses(dbresolver.Read)
}

func (g groupDo) WriteDB() IGroupDo {
	return g.Clauses(dbresolver.Write)
}

func (g groupDo) Session(config *gorm.Session) IGroupDo {
	return g.withDO(g.DO.Session(config))
}

func (g groupDo) Clauses(conds ...clause.Expression) IGroupDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g groupDo) Returning(value interface{}, columns ...string) IGroupDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g groupDo) Not(conds ...gen.Condition) IGroupDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g groupDo) Or(conds ...gen.Condition) IGroupDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g groupDo) Select(conds ...field.Expr) IGroupDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g groupDo) Where(conds ...gen.Condition) IGroupDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g groupDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IGroupDo {
	return g.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (g groupDo) Order(conds ...field.Expr) IGroupDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g groupDo) Distinct(cols ...field.Expr) IGroupDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g groupDo) Omit(cols ...field.Expr) IGroupDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g groupDo) Join(table schema.Tabler, on ...field.Expr) IGroupDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g groupDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGroupDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g groupDo) RightJoin(table schema.Tabler, on ...field.Expr) IGroupDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g groupDo) Group(cols ...field.Expr) IGroupDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g groupDo) Having(conds ...gen.Condition) IGroupDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g groupDo) Limit(limit int) IGroupDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g groupDo) Offset(offset int) IGroupDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g groupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g groupDo) Unscoped() IGroupDo {
	return g.withDO(g.DO.Unscoped())
}

func (g groupDo) Create(values ...*entity.Group) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g groupDo) CreateInBatches(values []*entity.Group, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g groupDo) Save(values ...*entity.Group) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g groupDo) First() (*entity.Group, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Group), nil
	}
}

func (g groupDo) Take() (*entity.Group, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Group), nil
	}
}

func (g groupDo) Last() (*entity.Group, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Group), nil
	}
}

func (g groupDo) Find() ([]*entity.Group, error) {
	result, err := g.DO.Find()
	return result.([]*entity.Group), err
}

func (g groupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Group, err error) {
	buf := make([]*entity.Group, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g groupDo) FindInBatches(result *[]*entity.Group, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g groupDo) Attrs(attrs ...field.AssignExpr) IGroupDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g groupDo) Assign(attrs ...field.AssignExpr) IGroupDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g groupDo) Joins(fields ...field.RelationField) IGroupDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g groupDo) Preload(fields ...field.RelationField) IGroupDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g groupDo) FirstOrInit() (*entity.Group, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Group), nil
	}
}

func (g groupDo) FirstOrCreate() (*entity.Group, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Group), nil
	}
}

func (g groupDo) FindByPage(offset int, limit int) (result []*entity.Group, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g groupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g groupDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g groupDo) Delete(models ...*entity.Group) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *groupDo) withDO(do gen.Dao) *groupDo {
	g.DO = *do.(*gen.DO)
	return g
}
