radium:
  http:
    port: "8080"
    read_timeout: 5s
    write_timeout: 5s
    idle_timeout: 3m
    max_header_bytes: 65000
  auth:
    password_cost_bcrypt: 13
    access_token_ttl: 2h
    refresh_token_ttl: 720h
    length_verification_code: 6

wave:
  http:
    port: "8081"
    read_timeout: 5s
    write_timeout: 5s
    idle_timeout: 3m
    max_header_bytes: 65000

postgres:
  max_open_conns: 40
  max_idle_conns: 10
  conn_max_idle_time: 5m
  conn_max_lifetime: 10m

smtp:
  host: connect.smtp.bz
  port: 2525
  length_verification_code: 6

centrifugo:
  token: "5d12cdf5-252f-4b04-a4e1-37aec016ef5c"
  api_key: "373b4d58-fe26-40a8-b5fc-00785ffc8450"
