basePath: /v1
definitions:
  entity.Course:
    properties:
      authors:
        items:
          $ref: '#/definitions/entity.User'
        type: array
      banner:
        type: string
      description:
        type: string
      id:
        type: string
      links:
        items:
          $ref: '#/definitions/entity.Link'
        type: array
      logo:
        type: string
      modules:
        items:
          $ref: '#/definitions/entity.Module'
        type: array
      name:
        type: string
      shortDescription:
        type: string
      slug:
        type: string
    type: object
  entity.CourseDto:
    properties:
      authors:
        items:
          $ref: '#/definitions/entity.UserDto'
        type: array
      banner:
        type: string
      description:
        type: string
      id:
        type: string
      links:
        items:
          $ref: '#/definitions/entity.Link'
        type: array
      logo:
        type: string
      modules:
        description: 'TODO: скрыть для людей, у которых нет доступа к курсу'
        items:
          $ref: '#/definitions/entity.ModuleDto'
        type: array
      name:
        type: string
      shortDescription:
        type: string
      slug:
        type: string
    type: object
  entity.CourseRequest:
    properties:
      authors:
        items:
          type: string
        type: array
      banner:
        type: string
      description:
        type: string
      links:
        items:
          $ref: '#/definitions/entity.Link'
        type: array
      logo:
        type: string
      name:
        type: string
      shortDescription:
        type: string
    type: object
  entity.FileDto:
    properties:
      location:
        type: string
    type: object
  entity.GroupName:
    properties:
      name:
        type: string
    type: object
  entity.Link:
    properties:
      courseId:
        type: string
      id:
        type: string
      link:
        type: string
      name:
        type: string
    type: object
  entity.Module:
    properties:
      courseId:
        type: string
      id:
        type: string
      name:
        type: string
      pages:
        items:
          $ref: '#/definitions/entity.Page'
        type: array
      slug:
        type: string
    type: object
  entity.ModuleDto:
    properties:
      name:
        type: string
      pages:
        items:
          $ref: '#/definitions/entity.Page'
        type: array
      slug:
        type: string
    type: object
  entity.ModuleRequest:
    properties:
      courseId:
        type: string
      name:
        type: string
    type: object
  entity.Page:
    properties:
      id:
        type: string
      moduleId:
        type: string
      name:
        type: string
      slug:
        type: string
    type: object
  entity.PageRequest:
    properties:
      courseId:
        type: string
      moduleId:
        type: string
      name:
        type: string
      slug:
        type: string
    type: object
  entity.PasswordUpdate:
    properties:
      current:
        type: string
      new:
        type: string
    type: object
  entity.RefreshToken:
    properties:
      refreshToken:
        type: string
    type: object
  entity.SectionAnswerVerdict:
    enum:
    - OK
    - WA
    type: string
    x-enum-varnames:
    - SectionAnswerOK
    - SectionAnswerWA
  entity.SectionChoiceAnswerDto:
    properties:
      answer:
        type: string
      id:
        type: integer
      section_id:
        type: integer
      verdict:
        $ref: '#/definitions/entity.SectionAnswerVerdict'
    type: object
  entity.SectionChoiceAnswerPost:
    properties:
      answer:
        type: string
      section_id:
        type: integer
    type: object
  entity.SectionChoiceDto:
    properties:
      cost:
        type: integer
      id:
        type: integer
      order_by:
        type: integer
      question:
        type: string
      score:
        type: integer
      slide_id:
        type: integer
      variants:
        items:
          type: string
        type: array
    type: object
  entity.SectionChoicePost:
    properties:
      cost:
        type: integer
      order_by:
        type: integer
      question:
        type: string
      slide_id:
        type: integer
      variants:
        additionalProperties:
          type: boolean
        type: object
    type: object
  entity.SectionMultiChoiceAnswerDto:
    properties:
      answer:
        items:
          type: string
        type: array
      id:
        type: integer
      section_id:
        type: integer
      verdict:
        $ref: '#/definitions/entity.SectionAnswerVerdict'
    type: object
  entity.SectionMultiChoiceAnswerPost:
    properties:
      answer:
        items:
          type: string
        type: array
      section_id:
        type: integer
    type: object
  entity.SectionMultiChoiceDto:
    properties:
      cost:
        type: integer
      id:
        type: integer
      order_by:
        type: integer
      question:
        type: string
      score:
        type: integer
      slide_id:
        type: integer
      variants:
        items:
          type: string
        type: array
    type: object
  entity.SectionMultiChoicePost:
    properties:
      cost:
        type: integer
      order_by:
        type: integer
      question:
        type: string
      slide_id:
        type: integer
      variants:
        additionalProperties:
          type: boolean
        type: object
    type: object
  entity.SectionQuestionAnswerDto:
    properties:
      answer:
        type: string
      id:
        type: integer
      section_id:
        type: integer
      verdict:
        $ref: '#/definitions/entity.SectionAnswerVerdict'
    type: object
  entity.SectionQuestionAnswerPost:
    properties:
      answer:
        type: string
      section_id:
        type: integer
    type: object
  entity.SectionQuestionDto:
    properties:
      case_sensitive:
        type: boolean
      cost:
        type: integer
      id:
        type: integer
      order_by:
        type: integer
      question:
        type: string
      score:
        type: integer
      slide_id:
        type: integer
    type: object
  entity.SectionQuestionPost:
    properties:
      answer:
        type: string
      case_sensitive:
        type: boolean
      cost:
        type: integer
      order_by:
        type: integer
      question:
        type: string
      slide_id:
        type: integer
    type: object
  entity.SectionTextPost:
    properties:
      markdown:
        type: string
      order_by:
        type: integer
      slide_id:
        type: integer
    type: object
  entity.Session:
    properties:
      expiresIn:
        type: string
      refreshToken:
        type: string
      userId:
        type: string
    type: object
  entity.SignIn:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entity.SignUp:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  entity.Tokens:
    properties:
      accessToken:
        type: string
      expiresIn:
        type: string
      refreshToken:
        type: string
    type: object
  entity.UpdateUserRequest:
    properties:
      avatar:
        type: string
      name:
        type: string
    type: object
  entity.User:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: string
      isVerified:
        type: boolean
      name:
        type: string
      password:
        type: string
      sessions:
        items:
          $ref: '#/definitions/entity.Session'
        type: array
      verificationCode:
        type: string
    type: object
  entity.UserDto:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: без юлерна
  version: "1.0"
paths:
  /account:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.UserDto'
      security:
      - ApiKeyAuth: []
      tags:
      - account
    patch:
      consumes:
      - application/json
      parameters:
      - description: Данные для обновления
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - account
  /account/password:
    patch:
      consumes:
      - application/json
      parameters:
      - description: PasswordUpdate
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.PasswordUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      tags:
      - account
  /auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: RefreshToken
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.RefreshToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Tokens'
      tags:
      - auth
  /auth/signIn:
    post:
      consumes:
      - application/json
      parameters:
      - description: SignIn
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Tokens'
      tags:
      - auth
  /auth/signUp:
    post:
      consumes:
      - application/json
      parameters:
      - description: SignUp
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SignUp'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.Tokens'
      tags:
      - auth
  /course:
    get:
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/entity.Course'
      security:
      - ApiKeyAuth: []
      tags:
      - course
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные о курсе
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.CourseRequest'
      responses:
        "201":
          description: created
          schema:
            $ref: '#/definitions/entity.CourseDto'
      security:
      - ApiKeyAuth: []
      tags:
      - course
  /course/{courseId}:
    get:
      parameters:
      - description: course id
        in: path
        name: courseId
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/entity.CourseDto'
      tags:
      - course
  /group:
    post:
      parameters:
      - description: GroupName
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.GroupName'
      responses:
        "201":
          description: created
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - group
  /join/group/{groupId}:
    patch:
      parameters:
      - description: group id
        in: path
        name: groupId
        required: true
        type: string
      responses:
        "200":
          description: created
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - group
  /module:
    post:
      parameters:
      - description: moduleRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.ModuleRequest'
      responses:
        "201":
          description: created
          schema:
            $ref: '#/definitions/entity.ModuleDto'
      security:
      - ApiKeyAuth: []
      tags:
      - module
  /section/choice:
    post:
      parameters:
      - description: создание секции c вариантом ответа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SectionChoicePost'
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/entity.SectionChoiceDto'
      security:
      - ApiKeyAuth: []
      tags:
      - section
  /section/choice/answer:
    post:
      parameters:
      - description: ответ на задание с вариантом ответа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SectionChoiceAnswerPost'
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/entity.SectionChoiceAnswerDto'
      security:
      - ApiKeyAuth: []
      tags:
      - section
  /section/multichoice:
    post:
      parameters:
      - description: создание секции c несколькими вариантами ответа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SectionMultiChoicePost'
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/entity.SectionMultiChoiceDto'
      security:
      - ApiKeyAuth: []
      tags:
      - section
  /section/multichoice/answer:
    post:
      parameters:
      - description: ответ на задание с несколькими вариантами ответа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SectionMultiChoiceAnswerPost'
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/entity.SectionMultiChoiceAnswerDto'
      security:
      - ApiKeyAuth: []
      tags:
      - section
  /section/question:
    post:
      parameters:
      - description: создание вопросительной секции
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SectionQuestionPost'
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/entity.SectionQuestionDto'
      security:
      - ApiKeyAuth: []
      tags:
      - section
  /section/question/answer:
    post:
      parameters:
      - description: ответ на вопрос
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SectionQuestionAnswerPost'
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/entity.SectionQuestionAnswerDto'
      security:
      - ApiKeyAuth: []
      tags:
      - section
  /section/text:
    post:
      parameters:
      - description: создвние текствой секции
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SectionTextPost'
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/entity.Page'
      security:
      - ApiKeyAuth: []
      tags:
      - section
  /slide:
    post:
      parameters:
      - description: создание слайда
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.PageRequest'
      responses:
        "201":
          description: ok
          schema:
            $ref: '#/definitions/entity.Page'
      security:
      - ApiKeyAuth: []
      tags:
      - slide
  /teacher/{userId}/group/{groupId}:
    post:
      parameters:
      - description: user id
        in: path
        name: userId
        required: true
        type: string
      - description: group id
        in: path
        name: groupId
        required: true
        type: string
      responses:
        "201":
          description: created
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - group
  /upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      responses:
        "201":
          description: created
          schema:
            $ref: '#/definitions/entity.FileDto'
      security:
      - ApiKeyAuth: []
      tags:
      - file
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
