basePath: /v1
definitions:
  entity.Name:
    properties:
      name:
        type: string
    type: object
  entity.PasswordUpdate:
    properties:
      current:
        type: string
      new:
        type: string
    type: object
  entity.RefreshToken:
    properties:
      refresh_token:
        type: string
    type: object
  entity.SignIn:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entity.SignUp:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  entity.Tokens:
    properties:
      access_token:
        type: string
      expires_in:
        type: string
      refresh_token:
        type: string
    type: object
  entity.UserDto:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: без юлерна
  version: "1.0"
paths:
  /account:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.UserDto'
      security:
      - ApiKeyAuth: []
      tags:
      - account
  /account/name:
    put:
      consumes:
      - application/json
      parameters:
      - description: Новое имя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.Name'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      tags:
      - account
  /account/password:
    put:
      consumes:
      - application/json
      parameters:
      - description: PasswordUpdate
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.PasswordUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      tags:
      - account
  /auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: RefreshToken
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.RefreshToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Tokens'
      tags:
      - auth
  /auth/signIn:
    post:
      consumes:
      - application/json
      parameters:
      - description: SignIn
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Tokens'
      tags:
      - auth
  /auth/signUp:
    post:
      consumes:
      - application/json
      parameters:
      - description: SignUp
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SignUp'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.Tokens'
      tags:
      - auth
  /course:
    get:
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - course
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: logo
        in: formData
        name: logo
        required: true
        type: file
      - description: chat
        in: formData
        name: chat
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: description
        in: formData
        name: description
        required: true
        type: string
      - description: kotlin, math и тд
        in: formData
        name: type
        required: true
        type: string
      responses:
        "201":
          description: created
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - course
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
